### ISSUE TITLE
Is APU.py select the wrong frame range?

### ISSUE THREAD

**Issue by ACitronella** [aayushjr/ASL-video#2]
In the process of selecting frames to be annotated in `APU.py` line 282 to 289
```python
for k in range(select_frames):
    sorted_idx = np.argsort(vid_scores_annotated)     # Sorts in ascending order
    selected_frame.append(sorted_idx[-1])             # Pick frame with highest score 
    vid_scores_annotated[sorted_idx[-1]] = -1000.     # Change score of selected frame 
    # Change score of nearby frames 
    range_low, range_high = max(sorted_idx[0]-4,0), min(sorted_idx[0]+5, num_frames)
    range_center = sorted_idx[-1]
    vid_scores_annotated[range_low:range_high] += dist_norm_mask[4-(range_center-range_low):4+(range_high-range_center)]
```
In the range calculation, why did you select the `sorted_idx[0]` instead of `sorted_idx[-1]`? Since you argsort at the beginning the frame that has the highest score should be at the `sorted_idx[-1]`.

or anything I missed?

**Comment by aayushjr** [comment]
That is a typo, it should be [-1] to select frames around the current selected_frame. It is fixed now. Previous version was inverting the argsort so it used [0] index which was changed to make it simpler, this line missed the update.
